<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Anne Chang">
<meta name="dcterms.date" content="2023-12-12">

<title>Surv727 Final Project: NYC Bike-share Usage Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="final_report_files/libs/clipboard/clipboard.min.js"></script>
<script src="final_report_files/libs/quarto-html/quarto.js"></script>
<script src="final_report_files/libs/quarto-html/popper.min.js"></script>
<script src="final_report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="final_report_files/libs/quarto-html/anchor.min.js"></script>
<link href="final_report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="final_report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="final_report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="final_report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="final_report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Surv727 Final Project: NYC Bike-share Usage Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Anne Chang </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 12, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level1">
<h1>1. Introduction</h1>
<section id="topic" class="level2">
<h2 class="anchored" data-anchor-id="topic">1.1 Topic</h2>
<p>This project analyzes how people in New York City use <a href="https://citibikenyc.com">Citi Bike</a>, their bike-sharing program. Using R packages <code>DBI</code>, <code>ggplot</code>, <code>ggmap</code>, and <code>dbplyr</code>, this project aims to discover:</p>
<ol type="1">
<li><p>The distribution of bike stations and their capacity</p></li>
<li><p>The usage of Citi Bike and whether it changes at different years or months</p></li>
<li><p>Whether the usage differs for different types of users</p></li>
</ol>
</section>
<section id="dataset" class="level2">
<h2 class="anchored" data-anchor-id="dataset">1.2 Dataset</h2>
<p>The dataset used for this project is “<a href="https://console.cloud.google.com/marketplace/product/city-of-new-york/nyc-citi-bike?project=surv-727-test-403119">NYC Bike Trip</a>”, a public database from the City of New York hosted on Google BigQuery. This dataset has 2 tables: “Citibike_stations”, which includes location and capacity data of more than 2000 bike stations in NYC; “Citibike_trips”, which includes data from 58 million bike trips in 2012 to 2018. Trip date, duration, start and end stations, and user type are important variables used in the analysis.</p>
</section>
<section id="github-repository" class="level2">
<h2 class="anchored" data-anchor-id="github-repository">1.3 Github Repository</h2>
<p>Please find the relevant files for this project at: <a href="https://github.com/annechang11/surv727-final-project" class="uri">https://github.com/annechang11/surv727-final-project</a>.</p>
</section>
</section>
<section id="analysis" class="level1">
<h1>2. Analysis</h1>
<section id="bike-station-analysis" class="level2">
<h2 class="anchored" data-anchor-id="bike-station-analysis">2.1 Bike Station analysis</h2>
<p>To begin the analysis, I connected to BigQuery and accessed the dataset using <code>dbConnect</code> from the <code>DBI</code> package.</p>
<p>I first checked how many working bike stations there are, defined as stations that have a non-zero number of bikes and are available for renting and returning bikes.</p>
<div class="cell">
<div class="knitsql-table">
<table class="table table-sm table-striped small">
<caption>1 records</caption>
<thead>
<tr class="header">
<th style="text-align: right;">num_of_working_stations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2086</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>There are 2086 working bike stations. I visualized their locations by storing the queried table as a R dataframe and plotting each stations on a NYC map using <code>ggmap</code>.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="final_report_files/figure-html/bike_station_map-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Fig 1: Citi Bike Stations in NYC</figcaption>
</figure>
</div>
</div>
</div>
<p>From Fig 1, we can see that as of 2018, the bike stations cover Manhattan, Brooklyn, Queens, and west side of Jersey City. (Note: areas that were expanded to after 2018, e.g.&nbsp;Bronx, are not included in the dataset).</p>
<p>Most bike stations have a capacity of under 25 bikes, showing as blue dots on the map, while some stations at Midtown to Lower Manhattan and downtown Brooklyn have a high capacity of 75 or more bikes, showing as orange dots on the map.</p>
<p>The mean number of bikes per station is 15.5, and the median is 12, suggesting again that most bike stations are small with exception of a few large stations with 75+ bikes.</p>
</section>
<section id="bike-trip-analysis-number-of-trips" class="level2">
<h2 class="anchored" data-anchor-id="bike-trip-analysis-number-of-trips">2.2 Bike trip analysis – number of trips</h2>
<p>Next, I analyzed the number of bike trips by year and month. I used the SQL EXTRACT function to obtain the year and month information for each trip from the database, and plotted the number of trips by year and month. Fig 2 below shows the result.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="final_report_files/figure-html/bike_trip_year_month_usage-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Fig 2: Number of bike trips by year and month</figcaption>
</figure>
</div>
</div>
</div>
<p>From Fig 2 we can observe two things:</p>
<ol type="1">
<li><p>The number of trips increased year by year from 2013 to 2017. The reason is likely twofold: over time more people started to know and use the shared bikes, and the bike program continued to expand their coverage and capacity, attracting more new users.</p></li>
<li><p>There is an apparent seasonal difference in terms of number of trips. January and February had the lowest numbers of trips likely due to the cold weather. As spring and summer arrived, the numbers of bike trips increasingly rose from March to September, and fell again in fall from October to December.</p></li>
</ol>
</section>
<section id="bike-trip-analysis-trip-duration" class="level2">
<h2 class="anchored" data-anchor-id="bike-trip-analysis-trip-duration">2.3 Bike trip analysis – trip duration</h2>
<p>Another factor to look at is the duration of trips. Fig 3 and Fig 4 below show the average trip duration (in minute) by year and by month.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="final_report_files/figure-html/trip_duration_by_year-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Fig 3: Trip duration by year</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="final_report_files/figure-html/trip_duration_by_month-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Fig 4: Trip duration by month</figcaption>
</figure>
</div>
</div>
</div>
<p>From Fig 3 and Fig 4, we can see that:</p>
<ul>
<li><p>The average trip duration increased over year, from about 14 minutes in 2014 to about 17 minutes in 2017. (Note: 2013 and 2018 data has missing months, so their average duration are not comparable to other years.)</p></li>
<li><p>There is a seasonal difference in terms of trip duration. The winter months have lower average trip duration (13-14 minutes per trip) than the summer months (16-17 minutes per trip).</p></li>
</ul>
</section>
<section id="bike-trip-analysis-user-types" class="level2">
<h2 class="anchored" data-anchor-id="bike-trip-analysis-user-types">2.4 Bike trip analysis – user types</h2>
<p>Besides year and month, another interesting variable is whether the bike trip is made by a “subscriber”, who holds an annual ridership plan, or a “customer”, who pays for a single trip or a day pass to ride the bike.</p>
<div class="cell">
<div class="knitsql-table">
<table class="table table-sm table-striped small">
<caption>2 records</caption>
<thead>
<tr class="header">
<th style="text-align: left;">usertype</th>
<th style="text-align: right;">num_of_trip</th>
<th style="text-align: right;">Avg_trip_time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Subscriber</td>
<td style="text-align: right;">46917572</td>
<td style="text-align: right;">13.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Customer</td>
<td style="text-align: right;">6191149</td>
<td style="text-align: right;">35.8</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>From the queried result above, we can see big differences among subscribers and customers in terms of their bike usage. First, subscribers took much more bike trips than customers – about 7 times more. Second, the trips taken by subscribers on average were around 13 minutes, while the trips taken by customers were much longer, on overage 35 minutes.</p>
<p>These differences are likely associated with the different purposes of trips: subscribers likely use the trip for commuting or short-distance connecting, while the customers are more likely to be tourists who bought a day pass or single ride pass and used the bike to tour NYC, and hence the longer trip duration.</p>
</section>
<section id="popular-bike-routes" class="level2">
<h2 class="anchored" data-anchor-id="popular-bike-routes">2.4 Popular Bike Routes</h2>
<p>Next, I analyzed the popular shared bike “routes”, defined as different combinations of a start station (where the bike was rented) and an end station (where the bike was returned). I used the SQL CONCAT function to concatenate the start and end stations to be routes, and looked at the number of trips for each route to understand its popularity. Below is the result of the top 10 most popular routes, their number of trips and average trip duration.</p>
<div class="cell">
<div class="knitsql-table">
<table class="table table-sm table-striped small">
<caption>Displaying records 1 - 10</caption>
<colgroup>
<col style="width: 73%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">route</th>
<th style="text-align: right;">num_of_trips</th>
<th style="text-align: right;">avg_duration</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Central Park S &amp; 6 Ave to Central Park S &amp; 6 Ave</td>
<td style="text-align: right;">55703</td>
<td style="text-align: right;">47.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Grand Army Plaza &amp; Central Park S to Grand Army Plaza &amp; Central Park S</td>
<td style="text-align: right;">25573</td>
<td style="text-align: right;">53.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Centre St &amp; Chambers St to Centre St &amp; Chambers St</td>
<td style="text-align: right;">19670</td>
<td style="text-align: right;">32.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Broadway &amp; W 60 St to Broadway &amp; W 60 St</td>
<td style="text-align: right;">19475</td>
<td style="text-align: right;">45.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">12 Ave &amp; W 40 St to West St &amp; Chambers St</td>
<td style="text-align: right;">18667</td>
<td style="text-align: right;">24.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">W 21 St &amp; 6 Ave to 9 Ave &amp; W 22 St</td>
<td style="text-align: right;">17509</td>
<td style="text-align: right;">5.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">W 21 St &amp; 6 Ave to W 22 St &amp; 10 Ave</td>
<td style="text-align: right;">15120</td>
<td style="text-align: right;">7.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">West St &amp; Chambers St to 12 Ave &amp; W 40 St</td>
<td style="text-align: right;">14353</td>
<td style="text-align: right;">24.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">West St &amp; Chambers St to West St &amp; Chambers St</td>
<td style="text-align: right;">14165</td>
<td style="text-align: right;">26.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">12 Ave &amp; W 40 St to 12 Ave &amp; W 40 St</td>
<td style="text-align: right;">13499</td>
<td style="text-align: right;">30.8</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>From the table, we can see that:</p>
<ul>
<li><p>There are some “routes” that share the same start station and end station. In fact, the top 4 routes are all this type of routes.</p></li>
<li><p>For routes that have different start and end stations, the most popular route is “12 Ave &amp; W 40 St to West St &amp; Chambers St”, which was taken 18667 times and for on average 24 minutes.</p></li>
<li><p>The next two popular routes with different start and end stations are quite similar. Both start from W 21 St &amp; 6 Ave, and end at W 22 St &amp; 9 Ave or W 22 St &amp; 10 Ave. These 2 routes have a volume of 17509 times and 15120 times, and the average duration is 5 minutes (to 9 Ave) and 7 minutes (to 10 Ave).</p></li>
</ul>
<p>However, when looking at popular routes taken by different types of users, we see very different patterns among subscribers and customers. Fig 5 shows the top 5 most popular routes taken by the subscribers, and Fig 6 shows those for the customers.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="final_report_files/figure-html/top_routes_by_subscriber-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Fig 5: Most popular bike routes taken by subscribers</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="final_report_files/figure-html/top_routes_by_customer-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Fig 6: Most popular bike routes taken by customers</figcaption>
</figure>
</div>
</div>
</div>
<p>We can see some interesting findings:</p>
<ul>
<li><p>Subscribers did short trips from one location to another, while customers tended to rent and return the bike at the same station.</p></li>
<li><p>The most popular routes taken by subscribers are all in Midtown Manhattan and are all short routes. I looked up the average trip duration for those routes and most of them are within 5-10 minutes.</p></li>
<li><p>On the other hand, customers liked to rent and return bikes at stations around Central Park and Broadway, and the duration on average lasted for half an hour to an hour, much longer than those routes taken by the subscribers.</p></li>
</ul>
</section>
</section>
<section id="conclusion" class="level1">
<h1>3. Conclusion</h1>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">3.1 Summary</h2>
<p>This project analyzes the usage of NYC bikeshare program from 2013 to 2018, focusing on the distribution of bike stations and their capacity, the number of trips and average trip duration, and the popular bike routes for different types of users. Visualizations are presented to help the reader grasp the information.</p>
<p>In conclusion:</p>
<ul>
<li><p>The number of bike trips and the average trip duration gradually increased year by year, suggesting that the program is growing and people in NYC are using the bikes more and more.</p></li>
<li><p>There are seasonal differences in terms of number of bike trips and trip duration. Both numbers are lower for the winter months than for the summer months.</p></li>
<li><p>Different types of users show very different shared bike riding behavior. The subscribers (who bought the annual ridership plan) did a lot of short trips, on average for 13 minutes. The most popular routes for subscribers are all 5-10 minute short routes in Midtown Manhattan. On the other hand, customers (who bought a single trip or day pass) did fewer trips than subscribers, but the average trip duration is about an hour. Customers tended to rent and return the bike at the same station. Stations around Central Park were the most popular for them.</p></li>
</ul>
</section>
<section id="limitation" class="level2">
<h2 class="anchored" data-anchor-id="limitation">3.2 Limitation</h2>
<p>There are a few limitations of the dataset and analysis:</p>
<ul>
<li><p>The bike station data does not include the time when the station was built, and does not include stations that were built after 2018. If such data was included, I would be able to look at the expansion of the bike station coverage and its relationship to bike usage, to see if there were interesting patterns to uncover.</p></li>
<li><p>The bike trip data does not specify which user had taken a trip, only that the trip was taken by a certain type of user. This is reasonable for confidentiality reasons. The limitation is that the unit of analysis can only be “trips”, not “users”, and there is no way to distinguish whether the trips were made by a single user or different users. It would be interesting to see whether the analysis based on “users” would arrive at different conclusions from the analysis based on “trips”, if some sort of unidentifiable user data could be provided.</p></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>